spring:
  application:
    name: "spring-buildpacks-poc"

# Customize Spring Boot Info actuator
info:
  java.vm.vendor: ${java.vm.vendor}
  java.version: ${java.version}
  application.name: ${spring.application.name}

# Expose all Spring Boot Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
